twelive/JUNGLE

- src/App.tsx
- src/store/getPbImageURL.ts
- src/store/useDataStore.ts
- src/store/useStorageStore.ts
Feat/usestoragehooks : CRUD 스토어 사용 예시 추가/ 이미지 URL 가져오는 스토어 / storage 이미지 가져오는 스토어 생성하였습니다.
✅ 달성도
75% 추후 이미지 업데이트 수정 삭제 기능 추가 예정입니다.
> Feat/usestoragehooks : CRUD 스토어 사용 예시 추가/ 이미지 URL 가져오는 스토어 / storage 이미지 가져오는 스토어 생성하였습니다.

- src/App.tsx
- src/GlobalStyles.ts
- src/theme.ts
> Feat: 반응형 구현 위한 미디어 쿼리, 스타일 작성

- src/components/JobPage/JobCodingTestBox.tsx
- src/components/JobPage/JobHeaderItem.tsx
- src/components/JobPage/JobSeekBox.tsx
- src/layout/Footer.tsx
- src/pages/JobCodingTestPage.tsx
- src/pages/JobInterviewPage.tsx
- src/pages/JobSeekPage.tsx
- src/pages/LandingPage.tsx
- src/routes.tsx
> Feat/job : 반응형 추가

- src/GlobalStyles.ts
> Feat: 반응형 margin 고정형 -> % 로 수정

- src/components/Button/HeaderButton.tsx
- src/components/Header/HeaderButtonGroup.tsx
Feat: HeaderButton 로그아웃 연결 하였습니다.
#82 
로그아웃 연결하였습니다
> Feat: HeaderButton 로그아웃 연결 하였습니다.

- src/layout/Footer.tsx
Related to #68
- 푸터 컴포넌트 반응형
- 푸터 글자 잘림 현상 해결
푸터 반응형 구현 완료 하였습니다.
> Feat/Footer: 반응형 구현

- src/components/MainPage/Category.tsx
- src/components/MainPage/CategorySection.tsx
- src/pages/MainPage.tsx
Closed to #67 
- 메인 페이지 반응형 구현 완료
완료하였습니다.
> Feat/Main: 반응형 구현

- package.json
- pnpm-lock.yaml
- src/App.tsx
- src/assets/community/community-banner1.svg
- src/assets/community/community-banner2.svg
- src/assets/community/community-banner3.svg
- src/client.ts
- src/pages/CommunityDetailPage.tsx
- src/pages/CommunityPage.tsx
- src/routes.tsx
- src/store/useDataStore.ts
- src/store/useEmailStore.ts
- src/types/CommunityProject.ts
- src/types/CommunityStudy.ts
- src/types/Users.ts
- src/types/database.ts
- supabase/.gitignore
- supabase/config.toml
useEffect 사용으로 속도저하 및 에러로 인하여 코드를 리액트 쿼리로 수정하였습니다.
마크업 수정 하였습니다.
supabase 데이터 타입 설정 및 관련된 패키지 다운로드
<br> - 스터디 버튼을 클릭 후 작성자의 이메일 부분만 데이터를 받아오면 스와이퍼 부분은 완성입니다.<br>
<br> - 프로젝트/ 스터디 버튼 스타일링 예정입니다.<br>
> Feat/community: 커뮤니티 메인페이지 리액트쿼리사용

- src/components/Button/HeaderButton.tsx
- src/components/Header/HeaderButtonGroup.tsx
- src/components/Header/HeaderMenu.tsx
- src/components/Header/HeaderMenuItem.tsx
- src/components/Header/HeaderTitle.tsx
- src/components/Logo.tsx
- src/components/ScrollDown.tsx
- src/layout/Footer.tsx
- src/layout/Header.tsx
- src/layout/MainHeader.tsx
- src/store/useHeaderMenuStore.ts
closed to #68 
- 헤더 컴포넌트 반응형 구현
- 메인 / 커뮤니티 헤더 수정
- 헤더 반응형 구현 완료
> Feat/Header : 헤더 컴포넌트 반응형 구현

- src/components/StudyPage/LikeButton.tsx
- src/pages/StudyPage.tsx
like 버튼을 이용해서 좋아요 토글버튼을 구현하여 유저 상태에서 id를 가져다가 해당 Id로 supabase에 넣어주었습니다.
LikeButton 좋아요 기능 구현 완료/ 도서 추천 파트 적용 완료하였습니다.
100%
> Feat: LikeButton 좋아요 기능 구현 완료/ 도서 추천 파트 적용 완료하였습니다.

- src/components/StudyPage/LikeButton.tsx
- src/components/StudyPage/TagButton.tsx
- src/pages/StudyPage.tsx
1.좋아요 버튼과 태그버튼에 타입 추가하였습니다.
2.기술 디깅 파트 리스트 렌더링 마크업하였습니다.
80%
부가적으로 북마크 기능 구현 후 마크업 일부 수정 예정입니다.
> Feat:좋아요버튼, 태그버튼 타입 추가/기술 디깅 파트 추가 마크업 완료하였습니다.

- src/client.ts
- src/pages/CommunityPage/CommunityPage.tsx
> Feat/Common: 절대 경로 반영

- src/components/StudyPage/TagButtonComponent.tsx
- src/routes.tsx
> Feat: 기술디깅 파트 라우터와 버튼 일부 수정 하였습니다.

- src/App.tsx
- src/components/Loading.tsx
Closed to #106 
- 로딩 컴포넌트 작업 완료하였습니다.
> Feat/Common: 로딩 컴포넌트 작업

- src/pages/JobPage/JobInterviewPage.tsx
- src/store/useCommentStore.ts
> Feat/job : 경로 수정 후 merge

- src/pages/StackListlPage.tsx
- src/pages/StackNewPage.tsx
StackListlPage 라우터 수정/ StackNewPage 새글 작성 페이지 완성하였습니다.
> Feat:StackListlPage 라우터 수정/ StackNewPage 새글 작성 페이지 완성하였습니다.

- src/App.tsx
- src/components/LoginModal.tsx
- src/components/StudyPage/StackDiggingItem.tsx
- src/components/StudyPage/StudyTitleGroup.tsx
- src/pages/StackDetailPage.tsx
- src/pages/StackListlPage.tsx
- src/pages/StackNewPage.tsx
- src/routes.tsx
- src/store/useAuthStore.ts
- src/types/StackDigging.ts
- src/types/StackDiggingDTO.ts
StackDiggingPart 타입스크립트 적용 및 기본 마크업 및 기능 완료하였습니다.
> Feat: StackDiggingPart 타입스크립트 적용 및 기본 마크업 및 기능 완료하였습니다.

- README.md
> Docs : README 초안 작성

- src/store/useAuthStore.ts
`options : {redirectTo: "jungler.vercel.app/main",}`
> Fix: redirect 경로 재수정 - test2

- src/api/useWrittingData.tsx
- src/components/MainPage/Category.tsx
- src/components/MyPage/WritingCategory.tsx
> Feat/Mypage: 작성한 글 렌더링

- src/store/useAuthStore.ts
> Fix: redirect 경로 이동

- src/store/useAuthStore.ts
Related to #159 
- 개발 환경, 배포 환경 자동 리디렉션 URL 설정
> Init: 리디렉션 URL 설정 Test 1

- src/store/useAuthStore.ts
Related to #159
- 리디렉션 .env 변수 수정
> Init: 리디렉션 URL 설정 Test 2

- src/layout/RootLayout.tsx
> Refactor: 헤더 경로 수정

- src/store/useAuthStore.ts
Closed to #159 
- 프로모션, 개발 환경에 따른 리디렉션 경로 설정 완료
- `import.meta.env.MODE`
> Refactor: 프로모션, 개발 환경 리디렉션 경로 최종 설정

- src/App.tsx
- src/pages/StackDetailPage.tsx
- src/pages/StackNewPage.tsx
- src/store/useDataStore.ts
stacknewpageaddedconsole 에러 처리를 위한 콘솔을 추가하였습니다.
> Feat/stacknewpageaddedconsole 에러 처리를 위한 콘솔을 추가하였습니다. 

- src/components/LandingPage/SectionComponentOne.tsx
- src/components/MyPage/ResumeLink.tsx
- src/components/MyPage/WritingCategory.tsx
- src/store/useHeaderMenuStore.ts
> Refactor: 에러, 리팩토링

- src/store/useHeaderMenuStore.ts
> Fix: 경로 오류 store 로직 수정

- src/components/LandingPage/LandingHeader.tsx
- src/components/LandingPage/SectionComponentFive.tsx
- src/components/LandingPage/SectionComponentFour.tsx
- src/components/LandingPage/SectionComponentOne.tsx
- src/components/LandingPage/SectionComponentThree.tsx
- src/components/LandingPage/SectionComponentTwo.tsx
- src/components/LandingPage/SectionScrollDownButton.tsx
- src/components/LandingPage/SectionScrollUpButton.tsx
- src/components/LandingPage/SectionThreeImgBox.tsx
> Refactor : 1차 반응형 리팩토링

- README.md
- src/components/LandingPage/LandingHeader.tsx
- src/components/LandingPage/SectionComponentFive.tsx
- src/components/LandingPage/SectionComponentFour.tsx
- src/components/LandingPage/SectionComponentOne.tsx
- src/components/LandingPage/SectionComponentThree.tsx
- src/components/LandingPage/SectionComponentTwo.tsx
- src/components/LandingPage/SectionScrollDownButton.tsx
- src/components/LandingPage/SectionScrollUpButton.tsx
- src/components/LandingPage/SectionThreeImgBox.tsx
> Develop -> Main: 배포

- src/components/LandingPage/SectionComponentThree.tsx
- src/components/LandingPage/SectionScrollUpButton.tsx
- src/components/LandingPage/SectionThreeImgBox.tsx
> Refactor : 2차 반응형 리펙토링

- src/pages/MainPage.tsx
closed #198 
closed #201 
- width 속성 값이 60%로 제한되어 있어 mobile 영역 100%로 수정하였습니다.
- styled-components 구성요소시 접두사로 Styled을 붙여서 구별하였습니다.
- 메인페이지 UI 리팩토링 완료하였습니다.
- 필요시 컴포넌트명 수정 예정입니다.
> Refactor: Main - UI 및 구성요소명 수정

- src/components/JobPage/JobCodingTestBox.tsx
- src/components/JobPage/JobInterviewBox.tsx
- src/components/LandingPage/SectionMotionDiv.tsx
- src/layout/Footer.tsx
> Feat/job : 반응형 UI 수정

- src/types/database.ts
> Fix: Update database.ts

- src/pages/MyPage/MyResumeDetailPage.tsx
> Fix: 배포 에러 해결

- src/components/StudyPage/CommentItem.tsx
- src/components/StudyPage/StackDiggingItem.tsx
- src/pages/StudyPage/StackListlPage.tsx
- src/pages/StudyPage/StudyPage.tsx
리스트 페이지 목록 스타일 변경과 댓글 UI 개선하였습니다.
> Refactor/studypart : 리스트 페이지 목록 스타일 변경과 댓글 UI 개선하였습니다.

- src/components/MyPage/BookMarkItem.tsx
- src/components/MyPage/WritingCategory.tsx
- 명화님 레이아웃 변경: `border` 추가
- 다음 기능 열심히 구현해오겠습니다 😿
> Design: 작성글 border 레이아웃 변경

- src/components/StudyPage/QueryBookMarkButton.tsx
> Feat: 쿼리 북마크 개선한 버튼입니다

- src/components/StudyPage/CommentItem.tsx
- src/components/StudyPage/LikeButton.tsx
- src/pages/StudyPage/StackListlPage.tsx
- src/pages/StudyPage/StudyPage.tsx
- src/store/useDataStore.ts
- src/types/database.ts
> Feat: 좋아요 버튼 수정 및 댓글 변동 사항 실시간 반영 적용

- src/components/Button/EditButton.tsx
- src/components/MyPage/ProfileResume.tsx
- src/pages/MyPage/ResemeDetailPage.tsx
- src/pages/MyPage/ResumeListPage.tsx
- src/pages/MyPage/ResumeNewPage.tsx
- src/routes.tsx
- src/types/database.ts
closed #233 
- 이력서 작성 페이지 완성
- 이력서 상세 페이지 기본 완성
- 이력서 리스트 페이지 완성
- 이력서 작성 페이지 추가 항목 생길 경우 보완 예정입니다.
- 이력서 상세 페이지 레이아웃 수정 예정입니다.
> Feat/Resume: 이력서 작성 및 리스트, 상세 페이지 1차 완성
